DROP DATABASE IF EXISTS myapp;

CREATE DATABASE myapp;
USE myapp;

CREATE TABLE USER
(
  USER_ID VARCHAR(30)
, PASSWORD VARCHAR(30)
, UNIQUE (USER_ID)
);

CREATE TABLE PRODUCT_NUTRITION_INFORMATION
(
  PRODUCT_ID INTEGER AUTO_INCREMENT
, CALORIE TEXT
, CARBOHYDRATE TEXT
, SUGERS TEXT
, SALT_NI TEXT
, PROTEIN TEXT
, PROVINCE TEXT
, CHOLESTEROL TEXT
, TRANS_FAT TEXT
, CAFFEINE TEXT
, SATURATED_FAT TEXT
, PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE DRINK
(
  DRINK_ID INTEGER AUTO_INCREMENT
, DRINK_TYPE_KOR TEXT
, DRINK_TYPE_ENG TEXT
, DRINK_HOT_ICE TEXT
, ALLERGY_TRIGGERS TEXT
, DRINK_SIZE TEXT
, DRINK_NAME_KOR TEXT
, DRINK_NAME_ENG TEXT
, DRINK_PRICE INTEGER
, DRINK_INFO TEXT
, DRINK_IMAGE TEXT
, NUTRITION_INFORMATION_NUMBER INTEGER
, PRIMARY KEY (DRINK_ID)
);


INSERT INTO USER VALUES ('admin', 'admin');