DROP DATABASE IF EXISTS myapp;

CREATE DATABASE myapp;
USE myapp;

CREATE TABLE PRODUCT_NUTRITION_INFORMATION
(
  PRODUCT_ID INTEGER AUTO_INCREMENT
, CALORIE TEXT
, CARBOHYDRATE TEXT
, SUGERS TEXT
, SALT_NI TEXT
, PROTEIN TEXT
, PROVINCE TEXT
, CHOLESTEROL TEXT
, TRANS_FAT TEXT
, CAFFEINE TEXT
, SATURATED_FAT TEXT
, PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE DRINK
(
  DRINK_ID INTEGER 
, DRINK_TYPE TEXT
, DRINK_HOT_ICE TEXT
, ALLERGY_TRIGGERS TEXT
, DRINK_SIZE TEXT
, DRINK_NAME_KOR TEXT
, DRINK_NAME_ENG TEXT
, DRINK_PRICE INTEGER
, DRINK_INFO TEXT
, NUTRITION_INFORMATION_NUMBER INTEGER
, PRIMARY KEY (DRINK_ID)
);

INSERT INTO DRINK VALUES (2, 'ESPRESSO', 'H', 'MILK', 'SHORT', '바닐라 플랫 화이트', 'Vanilla Flat White', 5900, '바닐라 플랫 화이트는 진하고 고소한 리스트레토 샷과 바닐라 시럽 그리고 스팀 밀크로 즐기는 진한 커피 라떼 입니다.', 1);
INSERT INTO DRINK VALUES (3, 'ESPRESSO', 'H', 'MILK', 'SHORT', '아메리카노', 'Amelicano', 4900, '아메리카노임', 2);
INSERT INTO DRINK VALUES (4, 'ESPRESSO', 'H', 'MILK', 'SHORT', '테스트음료', 'Test', 5000, '테스트임.', 3);
CREATE TABLE lists (
    id INTEGER AUTO_INCREMENT,
    value TEXT,
    testtest TEXT,
    PRIMARY KEY (id)
);

